#!/bin/sh
echo "BRANCH_NAME:" ${BRANCH_NAME}
echo "BRANCH_IS_PRIMARY:" ${BRANCH_IS_PRIMARY}
echo "CHANGE_ID:" ${CHANGE_ID}
echo "CHANGE_URL:" ${CHANGE_URL}
echo "CHANGE_TITLE:" ${CHANGE_TITLE}
echo "CHANGE_AUTHOR:" ${CHANGE_AUTHOR}
echo "CHANGE_AUTHOR_DISPLAY_NAME:" ${CHANGE_AUTHOR_DISPLAY_NAME}
echo "CHANGE_AUTHOR_EMAIL:" ${CHANGE_AUTHOR_EMAIL}
echo "CHANGE_TARGET:" ${CHANGE_TARGET}
echo "CHANGE_BRANCH:" ${CHANGE_BRANCH}